from time import sleep

print('\r|______________________|', end = '\r')
sleep(0.1)
print('\r|H_____________________|', end = '\r')
sleep(0.1)
print('\r|HE____________________|', end = '\r')
sleep(0.1)
print('\r|HEL___________________|', end = '\r')
sleep(0.1)
print('\r|HELL__________________|', end='\r')
sleep(0.1)
print('\r|HELLO_________________|', end = '\r')
sleep(0.1)
print('\r|HELLO T_______________|', end = '\r')
sleep(0.1)
print('\r|HELLO TI______________|', end='\r')
sleep(0.1)
print('\r|HELLO TIM_____________|', end = '\r')
print()
